plugins { id 'com.android.application' }

android {
    namespace 'com.botzlkhai.monitor'
    compileSdk 34

    defaultConfig {
        applicationId "com.botzlkhai.monitor"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

